name:          T-SQL style guide by John McCall
description:   A consistent code style guide for T-SQL to ensure legible and maintainable projects

url:           https://lowlydba.com/tsqlstyle.guide/
domain:        https://lowlydba.com/tsqlstyle.guide/

markdown:      kramdown
permalink:     pretty
highlighter:   rouge

kramdown:
    input: GFM
    hard_wrap: false
    toc_levels: "2,3"

gems:
    - jekyll-sitemap
